### ISSUE TITLE
Min letters on reviews

### ISSUE THREAD

**Issue by weareminigolf** [whynotearth/we-are-mini-golf-frontend#193]
remove the minimum number of caracters on the reviews

**Comment by freedannyv** [comment]
Fixed in my last PR

**Comment by weareminigolf** [comment]
What is PR?

On the link https://deploy-preview-194--weareminigolf.netlify.app/<https://deploy-preview-194--weareminigolf.netlify.app/final-ranking>
The minimum of characters for the review is still active.

My feedbacks are all based on this version but if there is a more advanced I’ll be happy to see if

[cid:8164FBD9-FEDB-45A1-A078-59CFB6179763-L0-001]

Sent from my iPhone

On 4 Mar 2021, at 07:54, Danny <notifications@github.com> wrote:

﻿

Fixed in my last PR

**Comment by freedannyv** [comment]
@weareminigolf PR is Pull Request. It's GitHub's labelling for 'my last file update' basically. You can find it at the top of the page where it say Pull Request and see all of the Closed pull requests (edits that have been accepted and merged to staging and also edits that weren't accepted and simply closed without merging). 

As it happened the min characters wasn't fixed in that PR, but now it is fixed.
